# Generated by Django 4.1 on 2024-03-04 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_task_team"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
