# Generated by Django 4.1 on 2023-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('suspended', 'suspended'), ('in-review', 'in-review'), ('in-progress', 'in-progress'), ('not-started', 'not-started')], max_length=20),
        ),
    ]
