# Generated by Django 4.1 on 2023-01-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('due_date',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('in-progress', 'in-progress'), ('in-review', 'in-review'), ('suspended', 'suspended'), ('completed', 'completed')], max_length=20),
        ),
    ]
