# Generated by Django 4.1 on 2024-03-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
        ("tasks", "0005_task_assignees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="teams.team",
            ),
        ),
    ]
